/**
 * @fileoverview Service for interacting with Google Generative AI (Gemini).
 * Handles prompt generation, API calls, error handling, and retries.
 */

const { GoogleGenerativeAI } = require("@google/generative-ai");

/**
 * Helper function to pause execution for a given number of milliseconds.
 * Used for exponential backoff during rate limits.
 * @param {number} ms - Milliseconds to delay.
 * @returns {Promise<void>}
 */
const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

/**
 * AIService class to manage interactions with the Gemini API.
 */
class AIService {
  /**
   * Initializes the AI service with the provided API key.
   */
  constructor() {
    this.genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
  }

  /**
   * Generates a neighborhood summary by searching Madlan based on the exact address.
   * @param {string} displayName - The official, fully-qualified address generated by OpenStreetMap.
   * @param {number} [retries=3] - The number of allowed retry attempts in case of network/API errors.
   * @returns {Promise<Object>} A structured JSON object containing the summary, education, transportation, future development, and Madlan URL.
   * @throws {Error} Throws an error if all retry attempts fail or a critical processing error occurs.
   */
  async getNeighborhoodInfo(displayName, retries = 3) {
    for (let attempt = 1; attempt <= retries; attempt++) {
      try {
        const aiModelName = process.env.GEMINI_MODEL || "gemini-2.5-flash";
        const model = this.genAI.getGenerativeModel({
          model: aiModelName,
          tools: [{ googleSearch: {} }],
          // יצירתיות מאוזנת: מאפשרת הסקה מרחוב לשכונה, אך שומרת על עקביות.
          generationConfig: {
            temperature: 0.4,
          },
        });

        const prompt = `
          אתה מומחה נדל"ן ישראלי. המטרה שלך היא לספק מידע על שכונות מגורים מאתר מדלן.
          קיבלת מתוך מערכת GPS את הכתובת הבאה: "${displayName}".
          
          פעל לפי הכללים והשלבים הבאים בדיוק מוחלט:
          1. המרה מרחוב לשכונה: אם הכתובת שקיבלת כוללת שם של רחוב ללא שכונה, חובה עליך קודם כל לבצע חיפוש ברשת כדי לגלות לאיזו שכונה שייך הרחוב (לדוגמה, רחוב אדמונית בעפולה שייך לשכונה C1, ורחוב משה רבנו בלוד שייך לשכונת גני איילון).
          2. מיקוד מוחלט בשכונה: ברגע שזיהית את השכונה הנכונה אליה שייכת הכתובת, עליך להתמקד אך ורק בה! היזהר מאוד שלא לזלוג לשכונות סמוכות באותה עיר (למשל, אל תבלבל בין "גני איילון" ל"גני יער" הסמוכות). התייחס רק לשכונה המקורית.
          3. מציאת הלינק: חפש בגוגל את השכונה שמצאת יחד עם שם העיר והמילה "מדלן", כדי למצוא את עמוד סקירת השכונה הרשמי שמתחיל ב- https://www.madlan.co.il/area-info/
          
          חובה עליך להחזיר אך ורק אובייקט JSON חוקי (Valid JSON)  בדיוק במבנה הבא (ללא שום טקסט, הסברים או תגיות לפני או אחרי). 
          אם לא מצאת את עמוד מדלן המדויק, אל תתנצל! פשוט חפש מידע כללי ברשת על השכונה ומלא את השדות כמיטב יכולתך, ובשדה madlanUrl שים מחרוזת ריקה "".
          כלל ברזל לתחביר: אסור בתכלית האיסור להשתמש במרכאות כפולות (") בתוך הטקסט של הערכים! אם אתה צריך לכתוב מרכאות או ראשי תיבות (כמו תמ"א), השתמש בגרש יחיד (') או כתוב ללא מרכאות כלל.
          
          {
            "madlanUrl": "הקישור לעמוד ה-area-info שמצאת במדלן (אם לא מצאת, שים מחרוזת ריקה)",
            "summary": "ציין את שם העיר והשכונה שהסקת + תקציר כללי על אופי האזור המבוסס על מדלן (עד 3 משפטים)",
            "education": "מידע על בתי ספר וחינוך בשכונה המדויקת בלבד",
            "transportation": "תחבורה ציבורית ונגישות בשכונה המדויקת בלבד",
            "futureDevelopment": "פיתוח עתידי בשכונה המדויקת בלבד"
          }
        `;

        const result = await model.generateContent(prompt);
        const response = await result.response;
        let text = response.text();

        // מנגנון חילוץ JSON עמיד
        const jsonMatch = text.match(/\{[\s\S]*\}/);

        if (!jsonMatch) {
          throw new Error("Model did not return any parsable JSON block.");
        }

        return JSON.parse(jsonMatch[0]);
      } catch (error) {
        console.error(
          `AI Service Error (Attempt ${attempt}/${retries}):`,
          error.message,
        );

        if (
          (error.status === 503 || error.status === 429) &&
          attempt < retries
        ) {
          const backoffDelay = 2000 * attempt;
          console.log(
            `API limitation (${error.status}). Waiting ${backoffDelay}ms before retry...`,
          );
          await delay(backoffDelay);
          continue;
        }

        if (
          attempt === retries ||
          (error.status !== 503 && error.status !== 429)
        ) {
          throw new Error("aiProcessingError");
        }
      }
    }
  }
}

module.exports = new AIService();
