/**
 * @fileoverview Service for interacting with Google Generative AI (Gemini).
 * Handles prompt generation, API calls, error handling, and retries.
 */

const { GoogleGenerativeAI } = require("@google/generative-ai");

/**
 * Helper function to pause execution for a given number of milliseconds.
 * Used for exponential backoff during rate limits.
 * @param {number} ms - Milliseconds to delay.
 * @returns {Promise<void>}
 */
const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

/**
 * AIService class to manage interactions with the Gemini API.
 */
class AIService {
  /**
   * Initializes the AI service with the provided API key.
   */
  constructor() {
    this.genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
  }

  /**
   * Generates a neighborhood summary in HEBREW by searching the web based on the exact address.
   * @param {string} displayName - The official, fully-qualified address generated by OpenStreetMap.
   * @param {number} [retries=3] - The number of allowed retry attempts in case of network/API errors.
   * @returns {Promise<Object>} A structured JSON object containing the neighborhood data in Hebrew.
   * @throws {Error} Throws an error if all retry attempts fail.
   */
  async getNeighborhoodInfo(displayName, retries = 3) {
    for (let attempt = 1; attempt <= retries; attempt++) {
      try {
        const aiModelName =
          process.env.GEMINI_SEARCH_MODEL || "gemini-2.5-flash";
        const model = this.genAI.getGenerativeModel({
          model: aiModelName,
          tools: [{ googleSearch: {} }],
          generationConfig: {
            temperature: 0.4,
          },
        });

        const prompt = `
          אתה מומחה נדל"ן ישראלי. המטרה שלך היא לספק מידע על שכונות מגורים למשתמשים.
          קיבלת מתוך מערכת GPS את הכתובת הבאה: "${displayName}".
          
          פעל לפי הכללים והשלבים הבאים בדיוק מוחלט:
          1. המרה מרחוב לשכונה: אם הכתובת שקיבלת כוללת שם של רחוב ללא שכונה, חובה עליך קודם כל לבצע חיפוש ברשת כדי לגלות לאיזו שכונה שייך הרחוב.
          2. מיקוד מוחלט בשכונה: ברגע שזיהית את השכונה הנכונה אליה שייכת הכתובת, עליך להתמקד אך ורק בה. היזהר מאוד שלא לזלוג לשכונות סמוכות באותה עיר. התייחס רק לשכונה המקורית.
          3. מציאת הלינק: חפש בגוגל את השכונה שמצאת יחד עם שם העיר והמילה "מדלן", כדי למצוא את עמוד סקירת השכונה הרשמי שמתחיל ב- https://www.madlan.co.il/area-info/
          4. אך אזהרה חמורה: **בשום פנים ואופן אל תזכיר את המילה "מדלן" או כל אתר אחר בטקסט שלך!** הצג את המידע כעובדתי ואובייקטיבי מטעמך.
          
          חובה עליך להחזיר אך ורק אובייקט JSON חוקי (Valid JSON) בשפה העברית, בדיוק במבנה הבא (ללא שום טקסט, הסברים או תגיות לפני או אחרי).
          אם לא מצאת את עמוד מדלן המדויק, אל תתנצל! פשוט חפש מידע כללי ברשת על השכונה ומלא את השדות כמיטב יכולתך. 
          כלל ברזל לתחביר: אסור בתכלית האיסור להשתמש במרכאות כפולות (") בתוך הטקסט של הערכים! אם אתה צריך לכתוב מרכאות או ראשי תיבות (כמו תמ"א), השתמש בגרש יחיד (') או כתוב ללא מרכאות כלל.
          
          {
            "neighborhoodName": "השם המלא של השכונה והעיר שהסקת (לדוגמה: 'גני איילון, לוד')",
            "summary": "תקציר כללי על אופי האזור (עד 3 משפטים. חובה ללא אזכור מקורות מידע!)",
            "education": "מידע על בתי ספר וחינוך בשכונה המדויקת בלבד",
            "transportation": "תחבורה ציבורית ונגישות בשכונה המדויקת בלבד",
            "futureDevelopment": "פיתוח עתידי בשכונה המדויקת בלבד"
          }
        `;

        const result = await model.generateContent(prompt);
        const response = await result.response;
        let text = response.text();

        const jsonMatch = text.match(/\{[\s\S]*\}/);
        if (!jsonMatch) {
          throw new Error("Model did not return any parsable JSON block.");
        }

        return JSON.parse(jsonMatch[0]);
      } catch (error) {
        console.error(
          `AI Service Search Error (Attempt ${attempt}/${retries}):`,
          error.message,
        );
        if (
          (error.status === 500 ||
            error.status === 503 ||
            error.status === 429) &&
          attempt < retries
        ) {
          const backoffDelay = 2000 * attempt;
          await delay(backoffDelay);
          continue;
        }
        if (
          attempt === retries ||
          (error.status !== 500 && error.status !== 503 && error.status !== 429)
        ) {
          throw new Error("aiProcessingError");
        }
      }
    }
  }

  /**
   * Translates a Hebrew neighborhood JSON object into English.
   * @param {Object} hebrewData - The original JSON data in Hebrew.
   * @param {number} [retries=2] - Allowed retries for translation.
   * @returns {Promise<Object>} The translated JSON object.
   */
  async translateNeighborhoodData(hebrewData, retries = 2) {
    for (let attempt = 1; attempt <= retries; attempt++) {
      try {
        const aiModelName =
          process.env.GEMINI_TRANSLATION_MODEL || "gemini-3.1-flash-lite";
        const model = this.genAI.getGenerativeModel({
          model: aiModelName,
          generationConfig: {
            temperature: 0.1,
            responseMimeType: "application/json",
          },
        });

        const prompt = `
          Translate the following Hebrew real estate JSON object into professional English.
          Keep the exact same JSON keys. Translate only the values.
          Do not include any other text, markdown, or explanations.
          
          Hebrew JSON to translate:
          ${JSON.stringify(hebrewData, null, 2)}
        `;

        const result = await model.generateContent(prompt);
        const response = await result.response;
        let text = response.text();

        return JSON.parse(text);
      } catch (error) {
        console.error(
          `Translation Error (Attempt ${attempt}/${retries}):`,
          error.message,
        );
        if (
          (error.status === 500 ||
            error.status === 503 ||
            error.status === 429) &&
          attempt < retries
        ) {
          await delay(1000 * attempt);
          continue;
        }
        if (attempt === retries) {
          console.warn(
            "Translation failed. Returning original Hebrew data as fallback.",
          );
          return hebrewData;
        }
      }
    }
  }
}

module.exports = new AIService();
